### ISSUE TITLE
Do we need the Dependabot config at all?

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/defectdojo-client-java#114]
Do we really need `.github/dependabot.yml` and name all ecosystems to check or can we simply remove the config and Dependabot will scan everything by default?

**Comment by Weltraumschaf** [comment]
@Ilyesbdlala 👀

**Comment by Ilyesbdlala** [comment]
Yes. A dependabot.yaml config has to be checked into the repo, for the dependabot to be enabled [[source](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/about-dependabot-version-updates#about-dependabot-version-updates)].
