### ISSUE TITLE
Automate publishing of DefectDojo Java Client release to maven central

### ISSUE THREAD

**Issue by Weltraumschaf** [secureCodeBox/defectdojo-client-java#35]
* https://docs.gradle.org/current/userguide/github-actions.html
* https://github.com/gradle/gradle-build-action

**Comment by J12934** [comment]
Mhh? It's automated: https://github.com/secureCodeBox/defectdojo-client-java/blob/main/.github/workflows/publish.yml
Getting automatically published when a github release is created.

**Comment by Weltraumschaf** [comment]
Build is automated, but there is no such release in [Maven Central](https://central.sonatype.com/search?smo=true&q=g%3Aio.securecodebox).

**Comment by J12934** [comment]
@Weltraumschaf should publish to maven central when the release doesn't contain snapshot
https://github.com/secureCodeBox/defectdojo-client-java/blob/main/build.gradle#L81

**Comment by Weltraumschaf** [comment]
Long time ago (~4 years) @rseedorff requested access to Maven Central. They said we should release some SNAPSHOT versions before they grant us access to the public repo. Now we should hook up this process.

**Comment by Weltraumschaf** [comment]
Found the Sonatype [OSSRH issue](https://issues.sonatype.org/browse/OSSRH-40107).

**Comment by Weltraumschaf** [comment]
We also need to meet some [requirements](https://central.sonatype.org/publish/requirements/#supply-javadoc-and-sources):

- Supply Javadoc and Sources
- Provide Files Checksums
- Sign Files with GPG/PGP
- Sufficient Metadata
- ...

**Comment by Weltraumschaf** [comment]
I've raised an comment in the [OSSRH issue](https://issues.sonatype.org/browse/OSSRH-40107) and asked how to add more mainatiners.

**Comment by Weltraumschaf** [comment]
[Gradle documentaton from sonatype](https://central.sonatype.org/publish/publish-gradle/)

**Comment by Zero3141** [comment]
Publishing requires that all files need to be signed with GPG/PGP. For that, we need the signing key together with its password in a ci run. We store these two Github's [Encrypted secrets](https://docs.github.com/en/actions/security-guides/encrypted-secrets).

### Signing key extraction (local)
First, we need to identify the LONG_ID of the private key:
```
gpg  --list-secret-keys
```

Then, we extract the private key:
```
gpg --armor --export-secret-keys <LONG_ID>
```
It should look like the following:
```
-----BEGIN PGP PRIVATE KEY BLOCK-----

...
-----END PGP PRIVATE KEY BLOCK-----
```

### Github release workflow
The release workflow runs `./gradlew sign`, which needs the following two environment variables being set: `SIGNING_KEY` and `SIGNING_PASSWORD`. In the workflow, they should be set from the preconfigured Github secrets `SIGNING_KEY` and `SIGNING_PASSWORD`.

**Comment by Weltraumschaf** [comment]
Real name: the secureCodeBox authors
E-Mail: securecodebox@iteratec.com
Comment: 
1. Master Key
2. Signing Key

**Comment by Weltraumschaf** [comment]
[Here](https://oss.sonatype.org/index.html#view-repositories;snapshots~browsestorage~/io/securecodebox/defectdojo-client/1.0.0-SNAPSHOT/defectdojo-client-1.0.0-20230703.130940-1.module) we can see our published snapshots.

**Comment by Weltraumschaf** [comment]
GPG Signing: We had the plan to use a sub key derived from a secret master key to sign the artifacts, bit it seems that [Maven can't deal with sub keys](https://central.sonatype.org/publish/requirements/gpg/#delete-a-sub-key). So we decided to use one dedicated GPG key only for our Java artifacts we deploy to Maven Central.

**Comment by Zero3141** [comment]
Its recommended to set an expiration date of [less than two years](https://riseup.net/ru/security/message-security/openpgp/gpg-best-practices#use-an-expiration-date-less-than-two-years) for our signing key. How do we keep track of this interval? @Weltraumschaf

**Comment by Weltraumschaf** [comment]
We add an appointment to the team calendar :-)

**Comment by Weltraumschaf** [comment]
We should really document all this stuff.

**Comment by Weltraumschaf** [comment]
We have the first release in [Maven Central](https://central.sonatype.com/artifact/io.securecodebox/defectdojo-client/1.0.0-alpha2)

**Comment by Weltraumschaf** [comment]
Open Todos:

- [ ] Automate next increment of Version like Maven does
- [ ] Test that nothing is published, if test fails
- [ ] Document release
- [ ] Make 1.0.0 Release

**Comment by Weltraumschaf** [comment]
We decided to change from Gradle to Maven bc full automatic release is not feasible int the we want it. We tried now for merely a week to get it work. With Maven it seems way more easier.

**Comment by Zero3141** [comment]
Problem: We enforce two status checks (DCO & Java Tests) to pass before merging. We already allowed the SCB Bot (who performs the push commit in which the version is bumped in the pom.xml) to push on the `main` branch. However, this setting mentions that `Required status checks will still prevent these people, teams, and apps from merging if the checks fail.`.

It seems like that this issue is a general issue, see [this discussion](https://github.com/orgs/community/discussions/13836).

**Comment by Zero3141** [comment]
We have weakened the branch protection rules to decouple the release process from [Issue 157](https://github.com/secureCodeBox/internal/issues/157). Close this now?

**Comment by Weltraumschaf** [comment]
@Zero3141 Can we add to the action that it updates the version in the README.md?

* https://github.com/secureCodeBox/defectdojo-client-java/blob/9a5811c5ac9dac52724ac00269e0dedc997c680b/README.md?plain=1#L21
* https://github.com/secureCodeBox/defectdojo-client-java/blob/9a5811c5ac9dac52724ac00269e0dedc997c680b/README.md?plain=1#L28
